# Generated by Django 2.2.5 on 2020-03-13 12:12

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeperregistration',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number with country code', max_length=31),
        ),
    ]
