# Generated by Django 2.2.5 on 2020-03-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_shopkeeperregistration_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopkeeperregistration',
            name='number',
        ),
    ]
